-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 28, 2017 at 05:05 PM
-- Server version: 10.1.26-MariaDB
-- PHP Version: 7.1.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `first_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `lyrics`
--

CREATE TABLE `lyrics` (
  `id` int(11) NOT NULL,
  `Title` text NOT NULL,
  `Singer` mediumtext NOT NULL,
  `Lyrics` text NOT NULL,
  `videoLink` mediumtext
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `lyrics`
--

INSERT INTO `lyrics` (`id`, `Title`, `Singer`, `Lyrics`, `videoLink`) VALUES
(1, 'Zingat', 'Ajay Gogavale', 'Urat hoti Dhad Dhad Lali Galavar Aali<br>Ana Angat Bharla Vaara he Preetichi Badha Zhali<br>Ara Urat hoti Dhad Dhad Lali Galavar Aali<br>Ana Angat Bharla Vaara he Preetichi Badha Zhali<br><br>Aata Adhir Jhaloya.. bagh Badhir Jhaloya<br>Ana Tujhyachsathi banun Majnu Maghe Aaloya..<br>Ana Udtoya Bungat Paltoya Chingat Rangat Aaloya<br>Zhala Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing<br><br>Zhala Zing Zing Zing Zing Zing Zing Zingat<br>Zhala Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing<br><br>Aata utavil Jhalo Gudgha Bashing Bandhal<br>Tujhya Navach Initial Tatoona Gondavl<br>Aata utavil Jhalo Gudgha Bashing Bandhal<br>Tujhya Navach Initial Tatoona Gondavl<br><br>Haat Bharun Aaloya?..<br>Haat Bharun Aaloya?..Laye Durun Aaloya..<br>Ana Karun Dadhi Bhari Perfume Marun Aaloya..<br>Aga Samdya Porat Mya Laye Jorat Rangat Aaloya..<br><br>Zhala Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing<br><br>Zhala Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing<br><br>Samdya Gavala Jhali Majhya Laganachi Ghai<br>Kadhi Honar tu Rani Majhya Lekrachi Aai<br><br>Samdya Gavala Jhali Majhya Laganachi Ghai<br>Kadhi Honar tu Rani Majhya Lekrachi Aai<br>Aata Tarat Jhaluya..<br>Aata Tarat Jhaluya.. Tujhya Gharat Aaluya<br>Laye Phirun Bandhavarun Kalti Marun Aaloya<br>Aaga Dhinchyak Jorat Techno Varat Darat Aaloya<br><br>Zhala Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing<br><br>Zhala Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing Zing Zing Zing Zingat<br>Zing Zing Zing', 'https://youtube.com/embed/2gcsgfzqN8k'),
(2, 'Hrudayat Vaje Something', 'Vidhit Patankar', 'Hrudayat vaje something<br>Saare jag vate happening<br>Astos sada mi aata dreaming (2 Times)<br><br>Ho?<br>Asto ugach smiling<br>Baghto tula man jumping<br>vate have god feeling<br>tararara<br>Asto ugach smiling<br>Baghto tula man jumping<br>vate have god feeling<br><br>Dhundh dhundh kshan saare<br>Halake halke fulnare<br>Firuni othanvar yei<br>Tujhech gaane (2 Times)<br><br>Khidkituni dokavuni<br>Distes ka pahato tula kshanokshani<br>Kalata tula mi sampato<br>Rokhu kashi dagmag ata rozchi<br><br>Najaretunich majhya sangato mi tula saare<br>Samjel ka tula kahi<br>Pahato jithe jithe mi chehara tujhach ahe<br>Visarto ka malach mi<br><br>Hrudayat vaje something<br>Saare jag vate happening<br>Astos sada aata dreaming (2 Times)<br><br>Vatevari mi rojchya asto ubha<br>Disachil ka kadhi tari<br>Disalis ki zankarte<br>Uthate mani kinkin hi god god ashi<br><br>Rokhuni mala tu baghshi<br>God tu jarashi hasashi<br>Yeshi an tashich tu jashi<br>Shabd na suche mag kahi<br>Bolane hi jamatch nahi<br>Gondhalun man he jai<br><br>Hrudayat vaje something<br>Saare jag vate happening<br>Astos sada aata dreaming (2 Times)', NULL),
(3, 'Bring it on Baby', 'Ajay-Atul', 'Aga Manaat Mazhya Aali,<br>Saadhi Nital Bhaavna,<br>Kiti Alone Rahu Aata,<br>Chala Couple Houna!<br>Bagh Tarhi Godit,<br>Luxury Gaadit,<br>Aaloya Mai Hoon ?Don?,<br>Bagh Tarhi Godit,<br>Luxury Gaadit,<br>Aaloya Mai Hoon ?Don?,<br><br>Baby Bring It On, Aalinganala<br>Bring It On, Aalinganala<br>Bring It On, Aalinganala<br>Bring It On!<br><br>Baby Bring It On, Aalinganala<br>Bring It On, Aalinganala<br>Bring It On, Aalinganala<br>Bring It On!<br><br>Aga Aliy Tu Gaavat,<br>Barachya Bhaavat,<br>Gelay Saarach Bhaan,<br>Ana Collejat Bhet.<br>Zaali Tujhi Maala Bhetun Vaatla,<br>Chaan!<br><br>Valakhpalakh Vaadhli Mhanun,<br>Laagli Tujhich Godi,<br>Aga Propose Maazha Tu Oppose Karun,<br>Kashi Ga Jamel Jodi!<br><br>Hoto Mya Kidkida,<br>Haad Bhi Kaadichi,<br>Gutkha Khaun Vaat Lagli,<br>Bodychi!<br><br>Yedagabalyala Rani,<br>Tuch Preet Daavli,<br>Tujhyavani Raani Mala,<br>Ek Nahi Bhaavli,<br>Faaltupana Bhi Gyala,<br>Navi Reet Ghaavli,<br>Tujhya Maag Maag Rani,<br>Mya Bhi Gym Laavli!<br><br>Ana Kartoy Zhumba,<br>Me Maartoy Bomba,<br>Na Haalat Zhaali Ghaan!<br><br>Ana Kartoy Zhumba,<br>Me Maartoy Bomba,<br>Na Haalat Zhaali Ghaan!<br><br>Baby Bring It On, Aalinganala<br><br>Bring It On, Aalinganala<br><br>Bring It On, Aalinganala<br><br>Bring It On!<br><br>Baby Bring It On, Aalinganala<br><br>Bring It On, Aalinganala<br><br>Bring It On, Aalinganala<br><br>Bring It On!<br><br>ATKT Madhi Zaaloya Paas,<br>Na Daddy Mhanala Baas,<br>Tari Tuzyamule Aaloya,<br>Collejala Mala Yeglaach Dhyaas,<br>Shejaar Gavachya Aaichya Bhavachya,<br>Lekicha Zaalay Class,<br>Aani Yeta Jaata Mala Khata Pita ,<br>Kasa Hotoya Tuzach Bhaas .<br><br>Karun Kharcha Lagin Laavu Thaatat,<br>Aan Tu Tar Saala Haat Deina Haatat,<br>Ekjiv Zaalyavani Raahu Dogh Jodin,<br>Raahu Dogh Jodin Mya Daru Biru Sodin,<br>Payment Zalyazalya Raani Don Gunthe Kadhin,<br>Bank Loan Kaadhun Mya Emi Phedin.<br><br>Gheun Mithit Saakhar Vaatit,<br>Vaghane Maarali Shaan,<br>Baby Bring It On? Aalinganala<br>Baby Bring It On? Aalinganala', NULL),
(4, 'Party De', 'Amitraj', 'Kiti Divas Jhale<br>Mala Fukatche Khaun<br><br>Roj Vaat Pahato Kdhi<br>Mhanto Swata Hun<br><br>Kiti Divas Jhale<br>Mala Fukatche Khaun<br>Ratri Nako Divsa<br>Chal Akkhi Nako Ardhi De?.<br><br>Varshatun Swata Hun<br>Ek Tari Party De<br>Party De Party De Melya<br>Party De Party De..<br>Party De Party De Melya..<br><br>Mitra Mitra Bolto Ani<br>Contry Karu Mhanto<br>Khishat Distat Paise Pan<br>Mich Nehami Gandato (2 Times)<br><br>Birthday La Hi Khayla Ghalto Starter<br>Tyat Tula Gift Dydyche Batter (2 Times)<br><br>Majhya Progress Sathi<br>Tu Thodishi Charity De<br>Ye De Na..<br><br>Varshatun Swata Hun<br>Ek Tari Party De<br>Party De Party De Melya<br>Party De Party De..<br>Party De Party De Melya..<br><br>He De Na He De Ne<br>He De Na He De Na;<br>Ek Tari De Na (3 Times)<br><br>Dostila He Ya Aplya<br>Najar Lavtat Jaam<br>Doghe Nuste Bhetalo Tari<br>Yana Futato Ghaam (2 Times)<br><br>Bhetu Jara Saumdit Re<br>Rahilya Ahet Gappa<br>Phone Karu Band<br>Ughdu Manatla Kappa (2 Times)<br><br>Sixty Nahi Magat<br>Chal 2 Thirty Thirty De<br><br>Varshatun Swata Hun<br>Ek Tari Party De<br>Party De Party De Melya<br>Party De Party De..<br>Party De Party De Melya..<br><br>Ek Tari De?', NULL),
(5, 'Yad Lagla', 'Ajay Gogavle', 'Yad Lagla Yad Lagla Ga<br>Rangla Tujhyat Yad Lagla Ga<br>Vaas Hyo Usaat Yee Kasturicha<br>Chakhalya Vaar Goad Lagla<br>Chand Bhastoa Disach Mawlaya Lagla g<br>Aas Lagli Mannat Kalvaya Lagla?<br><br>Yad Lagla Yad Lagla Ga<br>Rangla Tujhyat Yad Lagla Ga<br>Vaas Hyo Usaat Yee Kasturicha<br>Chakhalya Vaar Goad Lagla Ga<br><br>Sangavna Bolavna Maan Jhurtya Durun<br>Paltoya Taltya Valtya Maag Phirun<br>Sajlag Dhajlg Laag Kaajla Saarl<br>Yendhal hey Gondhala Laad Laad Gael Harun<br>Bhala Asa Urat Palvaya Laagla<br>Hey Oadh Lagli Manat Chalvaya Lagla<br>Yad Lagla Yad Lagla Ga<br><br>Hmm..<br>Hmm..<br>Hmm..<br><br>Sulgana Ulgana Jaal Aatlya Aatlya<br>Dukhn hey Dukhng Eklach Sathila<br>Kajlila Ujal Pajlun hya Vaatila<br>Chandnila Avtaar Dhadtuya Roj Ratrila<br>Zoap Lagna Sapan Jagvayla Lagla<br>Pakhru Kasa Abhal Panghraya Lagla<br><br>Hmm..<br>Hmm..<br>Hmm..', NULL),
(6, 'Sairat Jhala Ji', 'Ajay Gogavale', 'Alguj vaaj nabhaat<br>bhaltach zalaya aaj<br>algad aali manaat<br>pahilich tarani hi laaj<br><br>Ho?<br>Aga zananal kalajamandi<br>an hatamandi haat aal ji<br>sairat jhala ji?<br>sairat jhala ji?<br>sairat jhala ji?<br><br>Badlun gel ya saar<br>pirticha sutalaya vaar<br>allad Bhambhavalyala<br>billori paakharu nyaar<br>aal manaatal hya whatamandi<br>an hatamandi haat aal ji<br>sairat jhala ji?<br>sairat jhala ji?<br>sairat jhala ji?<br><br>Kavalya paanat hya<br>saavlya unhaat hya<br>paavlya manaat hya bharal.. bharal<br>tujh vamanamandi<br>ghumataay vaarya mandi<br>sur sanaicha raaya sajal<br>sajal un vaar nabhatana sajal<br>rangal man haldin raani rangal<br>saral he jagnyach jhuran saral<br>bhinal najren<br>ag dhadadal hya nabhamandi<br>an dholasang gaat aal ji<br>sairat jhala ji?<br>sairat jhala ji?<br>sairat jhala ji?<br><br>Aprit ghadlaya sapaan he padlaya<br>galayamandi sajalaya doral.. doral<br>saata janmach naat rujalaya kaaljat<br>tula r devagat pujal<br>rujala bij pritich sajani rujal<br>bhijal man pirmana purat bhijal<br>saral man maarun jagan saral<br>haral hya pirmala samad haral<br>kadalal paavasamandi<br>an abhalal yaat aal ji<br>sairat jhala ji?<br>sairat jhala ji?<br>sairat jhala ji?', NULL),
(7, 'Aatach Baya Ka Baavarla', 'Shreya Ghoshal', 'Halad Piwali, Por Kawli,<br>Zapun Lawa Gaali,<br><br>Sawalyacha Chahuleen, Paar Dawli Jhaali,<br>Gajar Jhala Daari,<br>Saajnachi Sawari, Saaj Nachi Sawari,<br>Aali Laaj Gaali Aali.<br><br>Japun Hotan Thhiwal Man Ho Kadhit Nahayi Jhurl,<br>Udhar Laga Ga Samdha Bai Hataat Nahai Ural,<br><br>Jeeva Jadla Par Nahayi Najrala Kadal,<br>Kiti Nadla Jikireen Maang Na Sarla,<br>Aatach Baya Ka Baavarla,<br>Kharcha Baya Ka Ghaabarla.<br><br>~~~~Insturmentals~~~~,<br><br>Saad Tu Ghatli, Raan Petun Aali,<br>Kavri Bawri, Laaz Daatun Aali,<br>Paahil Guman Bai, Ghetal Daman Bai,<br>Chetal Toofan, Sajnaa,<br>Bebhan Jhale Sajnaa,<br>Najrala Najracha, Najrana Kadhala,<br><br>Mann Iwala, Irghdala,<br>Ann Naata Jadhala,<br>Aatach Baya Ka Baavarla,<br>Kharcha Baya Ka Ghaabarla.<br><br>~~~~Insturmentals~~~~<br><br>Mann Jhaala Dhunda, Baajinda Lalkaari Ga,<br>Pirteecha Gandha Ananda Nawlayi Ga,<br>Laagli Oadh,<br>Lagli Oadh, Mann Hey Lyi Duaarh,<br>Satwun Jhaala Samdacha Gwaad,<br>Lagala Sajnila Sajnacha Yaarh.<br><br>Jhaaliya Bhool Hi, Umjali Ya Manala,<br>Partuni Ghaav Ha Lagla Ra Jiwala,<br>Dol Jhaklel Bai, Regh Akhlel Bai,<br>Maag Rekhlayal Sajna,<br>Udhdani Gail Sajna,<br>Harlaya Peermala, Peerman Jikala,<br>Jhagduni Mann Maajh Adbeen Jhukala,<br>Sajna Tu Sawrala.', NULL),
(8, 'Mala Ved Lagle', 'Bela Shende', 'Rang Bavrya Swapnana?. Sanga Re Sanga?<br>Kund Kalyana?Velina? Sanga Re Sanga?<br>He Bhas Hoti Kase? He Nav Othi Kunache?<br>Ka Sang Vedya Mana? Mala Bhan Nahi Jagache?<br>Mala Ved Lagle Premache?<br>Mala Ved Lagle Premache?<br>Premache? Premache?!!!<br><br>Nadavle, Dhundavle? Kadhi Guntale Man Bavre?<br>N Kale Kasa Konamule? Sur Lagle Man Mokle?<br>Ha Bhas Ki Tujhi Ahe Nasha?<br>Mala Sadh Ghalti Dahi Disha?<br>Mala Ved Lagle Premache?.<br>Mala Ved Lagle Premache?.<br>Premache? Premache?<br><br>Jagane Nave Vate Mala? Kuni Bhetala Majhe Mala?<br>Khulta Kali Umlun Ha? Man MOgra Gandhalala?<br>Ha Bhas Ki Tujhi Ahe Nasha?<br>Mala Sadh Ghalti Dahi Disha?<br>Mala Ved Lagle Premache?.<br>Mala Ved Lagle Premache?.<br>Premache? Premache?!!!', NULL),
(9, 'Shantabai', 'Sanjay Londe', 'Shantabai<br>Shantabai<br>Shantabai<br><br>Rupachi Khaan, Disati Chhan..<br>Lakhat Chhan, Najarecha Baan,<br>Tirkamaan, Mariti Chakra Tujha G Nakhara,<br>Ikdun Tikad Mariti Chakra,<br>Chakra-Nakhra,<br>Chakra-Nakhra<br>Chakra-Nakhra<br>Chakra-Nakhra, Chakra-Nakhra, Chakra-Nakhra<br><br>Shantabai<br>Shantabai<br>Shantabai<br>Aga Shantabai<br><br>Tera Ye Jalwa, Mahimcha Halwa..<br>Jivacha Kalwa, Manala Bhulwa..<br>Mamala Bolawa,<br>Kalwa-Halwa, Kalwa-Halwa, Kalwa-Halwa,<br>Shantabai<br>Shantabai<br>Shantabai<br>Aga Shantabai<br><br>Atak Matak Chavali Chatak,<br>Latak Matak Varyan Udati Kes Jhatak,<br>Latak-Matak, Latak-Matak, Latak-Matak<br>Shantabai Shantabai Shantabai<br><br>Khatapata Hicha Natapata,<br>Aho Patapata, Kasa Jhatapata,<br>Jeev Latapata Aahe Latapata,<br>Hicha Natapata Bagha Patapata<br>Kasa Natapata, Kasa Latapata,<br>Kasa Natapata, Kasa Latapata,<br><br>Shantabai<br>Shantabai<br>Shantabai<br>Aga Shantabai<br><br>Giraki Ghetiya Gara Gara,<br>Padar Udtoy Bhara Bhara<br>Hironi Disati Jara Jara<br>Tarr Rari Rararara<br><br>Shantabai<br>Shantabai<br>Shantabai<br>Aga Shantabai', NULL),
(10, 'Kitida Navyane', 'Mandar Aapte', 'Kitida navyane tula athvave<br>Dolyatle paani navyane vahave<br>Kitida navyane tula athvave<br>Dolyatle paani navyane vahave<br>Kitida navyane tula athvave<br>Dolyatle paani navyane vahave<br><br>Kitida zurave tujhyach sathi<br>Kitida mhanave tuze geet othi<br>Kitida zurave tujhyach sathi<br>Kitida mhanave tuze geet othi<br><br>Kitida sukuni punha fulave?.<br><br>Kitida navyane tula aathvave<br>Dolyatle paani navyane vahave<br>Kitida navyane tula aathvave<br>Dolyatle paani navyane vahave<br><br>Kiti haak dyavi tujhya manala<br>Kiti thambvave mi majhya dilala<br>Kitida raduni jeevane hasave<br><br>Kitida navyane tula aathvave<br>Dolyatle paani navyane vahave<br>Kitida navyane tula aathvave<br>Dolyatle paani navyane vahave', NULL),
(11, 'Tu Auron Ki', 'Benny Dayal', 'Dil ki ye gali udaas<br>Khaali Khaali ho gayi<br>Chaandni jo raat thi wo<br>Kaali Kaali ho gayi<br><br>Main to yahi chaahta hoon aaj bhi<br>Kaash tu bhi chaahti mujhe kabhi<br>Jab se  tu gayi hai jaana<br>Teri meri ye khushi bhi<br>Sad Sad khaali khaali ho gayi<br>Tu aaron ki?Kyun tu aaron ki ho gayi?<br><br>Thodi si khushi jo mili hai mujhe<br>Wo aaj chhup gayi hai jaane kahin<br>Jisey main chaahun ab dhoondna<br>Bina nashe ke wo milti hi nahi<br>Tujhe bhulaane ko ki nashe se dosti<br>Hai ab nasha, zindagi akele hum sahi<br>Jab se  tu gayi hai jaana<br>Teri meri ye khushi bhi<br>Sad Sad khaali khaali si ho gayi<br>Tu aaron ki?Kyun tu aaron ki ho gayi?<br><br>Hum wafaa ki raah par chale<br>Bewafaa humsafar ko liye<br>Hans padi hai manzilen hum pe<br>Bewajah humsafar hum hue<br>Humen wo puchhti kahan sahi hai hum sahi<br>Usey wafa ka kya pata main bewafaa nahi<br>Jab se  tu gayi hai jaana<br>Teri mera gam se dekh<br>Sad waali smiley send ho gayi<br>Tu aaron ki?Kyun tu aaron ki ho gayi?', NULL),
(12, 'Don?t control us', 'Siddharth Basrur', 'Jeene ke hain sau wajah<br>Le har maza tu ho ho ho<br>Khone ko saara jahaan<br>Ab daud jaa tu ho ho ho..<br>Aaj hi hai kal tera le faisla tu<br>Bandishon ko to tod jaa tu<br>Saansen Chala tu ho ho ho?<br><br>Roke hain na jaane kyun ye<br>Toke hain na jaane kyun ye<br>Karte hain na jaane kyun sawaal<br>Mere hain ye saare sapne<br>Band aankhon ke mere apne<br>Ghar mein ye karte hain kyun ye bawaal<br>Kyun na ye jaane hu pe na chalegi marzi<br>Zamaane humse?Zamaane se hum nahi<br>Don?t control us?Don?t control us?<br>Don?t control us?Don?t control us?<br><br>Hai khula ye jahaan chal chalaa..<br>Rok naa..naa re<br>Manchala hai chalaa?Bah gaya..<br>Yun tok naa?naa re.<br>Thokaron se dar nahi hai, Jaante sambhalna<br>Mushkilon ki roz leke jaan pe nikalna<br>Karegi Saari duniyaa salaam<br>Kyun na ye jaane?Hum pe naa chalegi marzi<br>Zamaane humse?Zamaane se hum nahi<br>Don?t control us?Don?t control us?<br>Don?t control us?Don?t control us?<br><br>Jaanun Main na jaane tu Kya hoga fir abhi<br>Par jeene ka hai maza Jab jiyo Zindagi<br>Maane tu na Maanu main Koi philosphy<br>Par apni strategy samjhe koi bhi nahi<br>Tune suna, Maine kaha? Zor chadha?Zor badha..<br>Kyun na ye jaane?Hum pe naa chalegi marzi<br>Zamaane humse?Zamaane se hum nahi<br>Don?t control us?Don?t control us?<br>Don?t control us?Don?t control us?', NULL),
(13, 'Kshitij Nave', 'Sayalie Pankaj', 'Kshitij Nave Maj Khunve<br>Gagan Nave Gungunte Ye Na? Ye Na<br>Jag Hey Nave Kavet Tujhya Ghe Na? Ghe Na?<br><br>Hurhur Hi Navi Navkhi<br>Roam Roam Adhir Ha<br>Adhirlya Majhyasave Hya Disha<br>Havi Havi Vaate Navi Hi Nasha<br><br>Kshitij Nave Maj Khunve<br>Gagan Nave Gungunte Ye Na? Ye Na<br>Jag Hey Nave Kavet Tujhya Ghe Na? Ghe Na?<br><br>Niras Purane Jagnyache Gaane<br>Shanbhar Te Visrunghe<br>Sur Chedu Manatle Ye Na? Ye Na<br><br>Kshitij Nave Maj Khunve<br>Gagan Nave Gungunte Ye Na? Ye Na<br>Jag Hey Nave Kavet Tujhya Ghe Na? Ghe Na?<br><br>Phikra Udyachi Chinta Parvachi<br>Roaj Chede Jiv Jale<br>Soadu Tila Varyavari Ye Na? Ye Na<br><br>Kshitij Nave Maj Khunve<br>Gagan Nave Gungunte Ye Na? Ye Na<br>Jag Hey Nave Kavet Tujhya Ghe Na? Ghe Na?', NULL),
(14, 'Datlele Dhuke', 'Rohit Raut', 'Datalele dhuke sare sare<br>Aarasa dakhavi tech khare<br>Bhas sakarata aaj janu<br>Kalajavar nasavet chare<br><br>Ya swapnana jagta jagata<br>Ye ayushyacha arth lau punha<br><br>Man phulpakharas nave<br>Alagad shwas shwas nave<br>Nakalat dhaga dhaga jodnara dua<br>Avkhal ya unad sari<br>Darval ha sukhacha jari<br>Hurhur lagata antari dhadhad lage punha<br><br>Visaruni ja vay dukkhache<br>Sukhat khol khol harvave<br>Athavanina dyave zoke<br>Kiti abol tol savarte', NULL),
(15, 'Lahan Majhi', 'Kalpana Patowary', 'Bhase jari kshanancha khel hi<br>Nakalat nisatate hatatun vel hi<br>He jagane aaj janu kataputali<br>Dor sute chal ithe bharkataleli<br>Haravali lahan majhi bahuli<br>Bhavatali sare badlun gele<br>Rutu badlachya sarkhe<br>Nikhalata tare andharun ale<br>Abhalach zale porakhe<br>Jau kute kajil tute<br>Vaat nase payatali<br>Haravali lahan majhi bahuli<br>Najar kunachi lagali sukhala<br>Hurhur shwasanmadhali<br>Bahar osarala fulranicha<br>Rikamya sugandhi onjali<br>Shodhu kiti vate bhiti<br>Papani hi panavali<br>Haravali lahan majhi bahuli<br>Haravali lahan majhi bahuli??', NULL),
(16, 'Pal Re Bhoplya', 'Jaanvee Prabhu Arora', 'Janken jilvis thapp he<br>Hevara he krish<br>School la late zala tar<br>Hoil tai tai fiss<br>Boring routine la pahije<br>Sunday chis weet dish<br>Office la late zala tar<br>Hoil tai tai fiss<br>Secondachya katya sobat lauya racing<br>Mirror madhe smiley wala pahuya feeling<br>Happy happy life cha funda so simple<br>Pal re bhoplya tunuk tunuk<br>Pal re bhopalya pal?<br>Comiks vachu de<br>No no abhyas ka<br>Pausat nachu de<br>No no no hoil fever<br>Comiks vachu de pausat nachu de<br>Cartoon pahu de<br>Karuya sari dhamal masti<br>Sutty tar lagu de<br>Secondachya katya sobat lauya racing<br>Mirror madhe smiley wala pahuya feeling<br>Happy happy life cha funda so simple<br>Pal re bhoplya tunuk tunuk<br>Pal re bhopalya pal?<br>Aapan aapale kadhu selfie<br>Ghaluya sweater khaun khau kulfie<br>Chandobachya Rappid la hi<br>Habbit nahi aplya salchi<br>Superfast jagtana rocketmadhe bastana<br>Bhetatil tare twinkle twinkle<br>Navi navi sims baghtana<br>Unch udave jari gharte japave jari<br>Secondachya katya sobat lauya racing<br>Mirror madhe smiley wala pahuya feeling<br>Happy happy life cha funda so simple<br>Pal re bhoplya tunuk tunuk<br>Pal re bhopalya pal?', NULL),
(17, 'Vate Vari', 'Praful Karlekar', 'Vate vari kate <br>Jari chalayche<br>Kode bharkatlele<br>Dhage gurfatlele jodayche<br><br>Ha anandi ashrunchi chav chakhuya<br>Satrangi swapnani jag jinkuya (X2)<br><br>Shodhuya punha chuklelya khuna<br>Zuklya papanya ughdavya<br>Khultana kalya hoti mokalya<br>Mitalya pakalya umlavya<br><br>Pasarle kiran ashanche<br>Visar andhar ha<br>Gavasale sur hi bhsanmadhale sparsh hota nava<br>Ulgadnara bandh natyatla<br>Gahivarnara hath hatata<br><br>Vate vari kate <br>Jari chalayche<br>Kode bharkatlele<br>Dhage gurfatlele jodayche<br><br>Ha anandi ashrunchi chav chakhuya<br>Satrangi swapnani jag jinkuya (X2)<br><br>Shodhuya punha chuklelya khuna<br>Zuklya papanya ughdavya<br>Khultana kalya hoti mokalya<br>Mitalya pakalya umlavya<br><br>Hooo???Aaaaaa???', NULL),
(18, 'Yena Yena', 'Sayalie Pankaj', 'Kshitij Nave Maj Khunve<br>Gagan Nave Gungunte Ye Na? Ye Na<br>Jag Hey Nave Kavet Tujhya Ghe Na? Ghe Na?<br>Hurhur Hi Navi Navkhi<br>Roam Roam Adhir Ha<br>Adhirlya Majhyasave Hya Disha<br>Havi Havi Vaate Navi Hi Nasha<br>Kshitij Nave Maj Khunve<br>Gagan Nave Gungunte Ye Na? Ye Na<br>Jag Hey Nave Kavet Tujhya Ghe Na? Ghe Na?<br>Niras Purane Jagnyache Gaane<br>Shanbhar Te Visrunghe<br>Sur Chedu Manatle Ye Na? Ye Na<br>Kshitij Nave Maj Khunve<br>Gagan Nave Gungunte Ye Na? Ye Na<br>Jag Hey Nave Kavet Tujhya Ghe Na? Ghe Na?<br>Phikra Udyachi Chinta Parvachi<br>Roaj Chede Jiv Jale<br>Soadu Tila Varyavari Ye Na? Ye Na<br>Kshitij Nave Maj Khunve<br>Gagan Nave Gungunte Ye Na? Ye Na<br>Jag Hey Nave Kavet Tujhya Ghe Na? Ghe Na?', NULL),
(19, 'Tujha Tu Majha Mi', 'Rupali Moghe', 'Jagu Thode Udhar<br>Kadhi Jinkun Haar<br>Diary Chya Paanavar<br>Jagnyachya Ooli Chaar<br><br>Jagu Thode Udhar<br>Kadhi Jinkun Haar<br>Diary Chya Paanavar<br>Jagnyachya Ooli Chaar<br><br>Hasu Radu Kadhi Ugach Chidu<br>Tujhya Saga Kadhi Swatala Mhanu<br>Tujha Majha Hishob Same Re<br>TTMM He<br><br>Hasu Radu Kadhi Ugach Chidu<br>Tujhya Saga Kadhi Swatala Mhanu<br>Tujha Majha Hishob Same Re<br>TTMM He<br><br>Chuklyavar Maffi Havi<br>Premat Baki Havi<br>Kadu Goad Ghotansathi<br>Tension free Coffee Havi<br><br>Chuklyavar Maffi Havi<br>Premat Baki Havi<br>Kadu Goad Ghotansathi<br>Tension free Coffee Havi<br><br>Hasu Radu Kadhi Ugach Chidu<br>Tujhya Saga Kadhi Swatala Mhanu<br>Tujha Majha Hishob Same Re<br>TTMM He<br><br>Hasu Radu Kadhi Ugach Chidu<br>Tujhya Saga Kadhi Swatala Mhanu<br>Tujha Majha Hishob Same Re<br>TTMM He<br><br>Tujha Tu Majha Mi<br>I don?t Care<br>Tujha Mi Majha Tu<br>Karun Baghu Share<br><br>Tujha Tu Majha Mi<br>I don?t Care<br>Tujha Mi Majha Tu<br>Karun Baghu Share<br><br>Hasu Radu Kadhi Ugach Chidu<br>Tujhya Saga Kadhi Swatala Mhanu<br>Tujha Majha Hishob Same Re<br>TTMM He<br><br>Hasu Radu Kadhi Ugach Chidu<br>Tujhya Saga Kadhi Swatala Mhanu<br>Tujha Majha Hishob Same Re<br>TTMM He', NULL),
(20, 'Man He', 'Shreya Ghoshal', 'Man He Tujhpashi Ramate<br>An Bhirbhirte<br>Harte Tan Vede Tujhsathi Ghutamalte<br><br>Man Tujhpashi Ramate<br>An Bhirbhrte<br>Harate Tan Vede Tujhsathi Ghutmalate<br><br>Bhay Ka Vate Mala<br>Sarnarya Lajeche Julnarya Gathiche Te Sarel Ka<br>Man He?<br><br>Man He?<br>Tujhpashi Ramate An Bhirbhrte..<br>Man He?.<br><br>Majhi Saath Tujhysathi<br>Jau.. Dur Nilya Kathi<br>Salsaltya Shwasat Tharthrtya Adharat<br>Mitlelya Dolyat He Disel Ka<br><br>Man He Tujhpashi Ramate An Bhirbhrte..<br>Harate Tan Vede Tujhsathi Ghutmalate<br><br>Aata Kay Kuna Sangu<br>Aata Kay Kuna Sangu<br>Majhe Roop Kase Pahu<br>Uthale He Kahur<br>Padali Ka Hi Bhool<br>Premachi Chahul Hi Asel Ka<br><br>Man He Tujhpashi Ramate An Bhirbhrte..<br>Harate Tan Vede Tujhsathi Ghutmalate<br>Bhay Ka Vate Mala<br>Sarnarya Lajeche Julnarya Gathiche Te Sarel Ka', NULL),
(21, 'Chi Va Chi Sau Ka', 'Swanand Kirkire', 'Ek Ahe Chiranjiv An Ek Ahe Chi Sau Ka\r\nShree Anee Sau Chya Adhi Chi Va Chi Sau Ka\r\n\r\nHe Mulaga Mulgi Lover Lovery\r\nBakpantit Navara Navri\r\nZatpat Chatpat Prem Visruni\r\nPatpat Patpat Deti Mg Te Ekmekana Bukka\r\n\r\nChi Ani Chi Sau Ka\r\nShree Ani Sau Chya Adhi Chi Ani Chi Sau Ka\r\n\r\nHi Kanya Diste Sunder\r\nAn Samjutdar Hushar An Khari\r\nHa Mulaga Disto Ahe Wonderful\r\nAn Kartabgar Khara\r\n\r\nYanche Hoil Ka Kahi\r\nJultil Mane Ka Nahi\r\nHoil Story Ka Aghvachi\r\nKi Romantikata Jail Sari\r\nBhalti Valane Gheil Kahi\r\nDhad Dhad Vadhun\r\nApuli Gadbad Badbad Gadbad Kartil\r\nTe Navare Aani Bayakka\r\n\r\nChi Va Chi Sau Ka\r\nShree Ani Sau Honya Adhi Chi Chiv Chiv Sau Ka\r\n\r\nHe Kiti He Varvar An Zarzar Down Hot Ahe\r\nAn Ka He Karnaryana Kahich Ka Samjat Nahi Ahe\r\nHo Premacha Bhang Hoi Ghatacha Spot Hoi\r\nHoti Raade He Kiti He\r\n\r\nRomantic Hi Comedy\r\nAn Happy Ending Around Corner\r\nVaat Pahati Tumhi Sagale\r\nAn Umchya Madhle Sagale Navare Ani Bayakka\r\nChi Ani Chi Sau Ka\r\nShree An Sau Mister Misses Honya Aadhi\r\nChiv Chiv Chi Va Chi Sau Ka\r\n\r\nHo Mulaga Mulgi Lover Lovery\r\nBakpantit Navara Navri\r\nZatpat Chatpat Prem Visruni\r\nPatpat Patpat Deti Mag Te Ekmekana Bukka\r\n\r\nChi Ani Chi Sau Ka\r\nShree Ani Sau Honya Adhi Chi Chiv Chiv Chi Sau Ka\r\n\r\nChi Ani Chi Sau Ka\r\nChi Ani Chi Sau Ka\r\nChi Ani Chi Sau Ka\r\nChi Ani Chi Sau Ka', NULL),
(22, 'Kshan Mohare', 'Shreya Ghoshal', 'Kshan Mohare Man Bahare\r\nBagh Vaat Hi.. Bolavate?\r\nTujhyasave Jag He Ata\r\nNave Disate\r\n\r\nMan Halave Bavarte\r\nTu Pahata? Savarte?\r\nTujhyasave Mihi Re Navi\r\n\r\nVaryavarti Udato..\r\nHo?? Ata Abola Jara\r\nHasnyachya Latanahi Sparshacha Kinara\r\n\r\nMe Haravto Majhya Madhe\r\nMag Tu Tithe.. Sapadte?.\r\nTujhyasave Jag He Ata\r\nNave Disate?..\r\n\r\nAndhar Padude Tithe Hi\r\nTu Hoshil Tara\r\nAbhal Barsu De Saare\r\nTu Majha Nivara\r\n\r\nTu Sobati Astana Mi Ekti Bhirbhirte\r\nTujhyasave Jag He Ata\r\nNave Disate', NULL),
(23, 'Kashi Mi Jau Mathurechya Bajari', 'Bela Shende', 'Dahidudh loni ghagar bharuni neu kashi bajari\r\nbavarle mi savarle g jau kashi chorun bai\r\nmadhurechya bajari?kashi mi jau mathurechya bajari ?\r\n\r\nnatkhat bhari kisnmurari tapala yamunatiri\r\nkartoy khodi ghagar fodi jau kashi chorun bai\r\nmadhurechya bajari?kashi mi jau mathurechya bajari ?\r\n\r\nnakos fodu kanha mazi ghagar aaj rikami\r\nhasel sari gokul nagari hoil re badnami\r\naaj dili bagh nandkishora hati laaj tujya re\r\nritich ghagar nashibi mazya, sharan tula mi ale\r\ndeva sharan tula mi aale\r\n\r\nvaat advun hasato gali g venu aikun mohit zale\r\nbhaan harpuni ramati gopika, shyamrangi nhaun gele\r\nman bhulavi asa kanha zulavi asa ha natnagar giridhari\r\ntyachya sang dangale, ras rangale, pirtichi reet nyari\r\nmadhurechya bajari?kashi mi jau mathurechya bajari ?', NULL),
(24, 'Dil Lafanga', 'Vishal Mishra', 'Uchale daaye baaye\r\nKisi se na ye sharmaye\r\nLove ka ye tution padhaye\r\nDil hai lafanga bada\r\n\r\nApni hi dhun pe nache\r\nApni dhun ye gaaye\r\nKahi bhi ye disko banaye\r\nDil hai lafanga bada\r\n\r\nDJ pe je bol ke\r\nParty tu karle yahi\r\nSath mere khub ke\r\nKhud ko ghumale kahi\r\n\r\nOpen dance floor hai\r\nMusic ka bhi shor hai\r\nKis ka kispe jor hai\r\nDil hai lafanga bada (2 Times)\r\n\r\nSun be o kake\r\n2 Pack tika ke\r\nMusic laga ke\r\nMai dansunga dansunga\r\n\r\nSare sitaro hona zukake\r\nBightness badha ke\r\nMai dansunga dansunga\r\nAage piche uper niche\r\nDaaye baaye rock an roll baja le\r\nChick pick toothpick\r\nKaano me hai sandwitch\r\nPicknick yahi mana le\r\n\r\nFunn ki bottle pool me\r\nDubki laga le yehi\r\nSath mere cruize par\r\nKhud ko ghuma le abhi\r\n\r\nOpen dance floor hai\r\nMusic ka bhi shor hai\r\nKis ka kispe jor hai\r\nDil hai lafanga bada (2 Times)\r\n\r\nChand ko yuv Bandh le tu\r\nHaath me leke Satyh me\r\nnacche wo sang hoke\r\nPighale tu masti yo me\r\nParty hoke muskuraye sabere\r\nSaari raat dance ho Subah na aane de\r\nDub ja jashn me beet ko chane de\r\n\r\nZindaggi to dance hai\r\nDil ko uchalu kahi\r\nSath me mere Cuize pe\r\nKhud ko ghuma le abhi\r\n\r\nOpen dance floor hai\r\nMusic ka bhi shor hai\r\nKis ka kispe jor hai\r\nDil hai lafanga bada (2 Times)\r\n\r\n', NULL),
(25, 'Pune RAP', 'Shreyash Jadhav', 'Kay kasa kay\r\nbara chalay na sagla\r\npune rap.. pune rap\r\n\r\nEk te char\r\nek te char\r\nsaare pasaar\r\nmag jag budo\r\nno karbhaar\r\nno karbhaar\r\nek te char.. saare pasaar\r\n\r\nVaran bhatana.. tupachya dharena\r\nlimbachya fodina.. baykochya jodina\r\ndeun tanuna.. aaram karu\r\nsayankali mag.. dolat dolat\r\nurmat bolata.. jagachi maapa\r\nkadhayala suru\r\n1.. 2.. 3.. Go..\r\n\r\nAamhi jomat.. punekar\r\nduniya komaat.. punekar\r\nchapkhal uttar.. punekar punekar\r\nhatacha antar.. punekar punekar\r\naklecha saagar.. punekar\r\ngodit jahar.. punekar\r\naakhiv.. rekhiv.. ati creative..\r\npatyancha kahar.. punekar\r\n\r\nHey vadhiv aamche pune.. ithe hotat paach be dune\r\naamhich keval darja.. ani baki saare khare daane\r\nsaaryanna gharane.. ithe saarech did shahane\r\naamchya pudhe nahi koni.. kon aahe re tikde\r\nkone kone\r\n\r\nDhotar wale.. pagdi wale\r\naamhi puneri\r\nSP Modern FC wale\r\naamhi puneri\r\nskarf bandhun.. rider muli\r\naamhi puneri\r\nhey suddha spashta swachha\r\naamchi boli.. aamhi puneri', NULL),
(26, 'Lagin Ghaai', 'Manasi Joshi', 'Laggin Laggin Ghaai..\r\nZali hila, Laggin Laggin Ghaai..\r\nBagh ga saye geli kuth raani?\r\ngod kiti rankalyaach paani\r\nith? naay naay\r\ntith? naay naay\r\nithbi naay an tithbi naay\r\n\r\nBagh ga saye geli kuth raani?\r\n\r\nangnaat? nhaai nhaai\r\nPadsaat? nhaai nhaai\r\nMalyaat? nhaai nhaai\r\nKhalyaat? nhaai nhaai\r\nAlyaad palyaad kuth bi nhaai raani?\r\n\r\nBagh ga saye geli kuth raani?\r\n\r\nRaani khushhal haay\r\nhaay tari kut?\r\nJara laajat haay\r\nhaay tari kut?\r\nRajachya sangtin ghodyavar jaaya\r\nsajat haay, laajat haay, Murkat haay, hasat haay\r\naata laava halad hichya gaali\r\nghaaai kara varaat nighaali?\r\n\r\nRaaja joshat haay\r\nlai jomaat haay\r\nbharamacharyach vrat hyaach\r\nHaay haay haay?\r\naahrr.. gadi mardana pailvaan tu\r\nasa kasa gela paatavar haladichya\r\nkiti bi saangun samjayaa nhaay?\r\nTu ?Irun Firun Gangavesh? sukkalichya..\r\n\r\nLaggin Laggin Ghaai..\r\nZali hila, Laggin Laggin Ghaai..\r\nLaggin Laggin Ghaai..\r\nZali hyala, Laggin Laggin Ghaai..', NULL),
(27, 'Antaricha', 'Vishal Mishra', 'Antaricha sur halkech asa umatala\r\nJeev maza algad tujhyasave nisatala\r\nAntaricha sur halkech asa umatala\r\nJeev maza algad tujhyasave nisatala\r\n\r\nMan vede hoyi tujhiyasathi\r\nAas sarena hi\r\nAlawar dena sad de na ya mana\r\nSakhe bol na kahi\r\n\r\nGandh ola dur varyavar kasa haravla\r\nJeev maza algad tujhyasave nisatala\r\n\r\nHaravlya jeeva aaj kase sangave\r\nReshami sari ghaav kiti sosave\r\nSwapn sajare aahe ajuni japlele\r\nShimplyatuni moti ole sajalele\r\n\r\nYa vatanvarti disti ajunhi ka khuna sarlya\r\nAabhas he ka hoti aajuni savalya urlya\r\nShwass maza nakalat tujhyat ch gntala\r\nJeev maza algad tujhyasave nisatala\r\n\r\nAntaricha sur halkech asa umatala\r\nJeev maza algad tujhyasave nisatala\r\nAntaricha??.\r\nJeev maza ??', NULL),
(28, 'Halad Lagali', 'Anand Shinde', 'Swapnatali majhya pari\r\nkal hogi bayko gomari (2 Times)\r\n\r\nKandil asa halavala\r\nZatase ye porgi patali\r\nHaldicha ha bahana\r\nAaj ghalu dhingana\r\nAisi khushi chai\r\nHo gaya mai deewana\r\nJulalai lagnachi bedi\r\n\r\nHalad lagali halad lagali (3 times)\r\n\r\nUchi uchi nako feku tu pora\r\nDuniyadaricha ha sod tora (2 Times)\r\nTere jaise yaha 56 hai ashiq\r\nYeti jamin aur yeti majhya dara\r\nChal maar tu kalti..\r\n\r\nMujhko sikhana tu shaanatii\r\nSunke mera naam hai sabki fatati\r\nMard marathyacha tevar ha sara\r\nLakhatala mi tuza dilwala\r\nLakhatala mi tuza dilwala\r\n\r\nHaldicha ha bahana\r\nAaj ghalu dhingana\r\nAisi khushi chai\r\nHo gaya mai deewana\r\nJulalai lagnachi bedi\r\n\r\nHalad lagali halad lagali (3 Times)\r\n\r\nPremache he bandh aaj nave julale..\r\nYa manache tya manala kalale (2 Times)\r\nBhavananche he abol nate\r\nAntari ya apulya khulale\r\n\r\nAaja bhidu hosh me tu?\r\nMere yaar tu kho gaya hai kidhar tu\r\nDekh jara setting teri ye idhar\r\nDil me chupa hai jo kuch bhi tere\r\nBol de fultoo hoke idhar tu\r\n\r\n Haldicha ha bahana\r\nAaj ghalu dhingana\r\nAisi khushi chai\r\nHo gaya mai deewana\r\nJulalai lagnachi bedi\r\n\r\nHalad lagali halad lagali (3 times)', NULL),
(29, 'Dolbywalya', 'Nagesh morwekar', 'Porr Jamali Yeshivarati\r\nCharcha Boring Zaali\r\nChal Re Bhaavadya Party La\r\nMag Paaravarati Aali\r\nTapari Maage Rachali Quarter\r\nBhaavadya La Mag Basala Starter\r\nChal Re Pintya Mitavu Aapalya\r\nDisko Dancing Khaajela\r\nDolbywalya Bolaav Mazya DJ La DJ La?..\r\nDolbywalya Bolaav Mazya DJ La DJ La?.(2 Times)\r\n\r\nArr Varhadi Nasun Ha\r\nVaraati Madhe Ghusato Nachaaya\r\nAnn Zingun Zingun Nachala Ha\r\nNisat Laagude Vajaaya (2 Times)\r\nAala Miravanukit?. Bhaavadya\r\nKadhi Dandiya Kheltuya?. Bhaavadya\r\nHandi Fodaaya Var Govinda\r\nKhali Nachun Ghetoy Bhaavadya\r\nTanga Palati Sutale Ghode\r\nPant Faatun Tutale Jode\r\nGirakya Gheto Karun Sadara\r\nDeto Sodun Laajela\r\nDolbywalya Bolaav Mazya DJ La DJ La?..\r\nDolbywalya Bolaav Mazya DJ La DJ La?.(2 Times)\r\nAala DJ Bhi Rangaat\r\nKhetun Khetun Laavato Item\r\nBhaavadya Bharun Gallas\r\nKarato Khallas Top To Bottom (2 Times)\r\nAala Recharge Maarun Bhavadya\r\nKasa Lezim Khelato Bhavadya\r\nBasala Damun Kadala Pintya\r\nTyala Khechun Odhtoy Bhavadya\r\nLaat Ghaalun Mhanla Sorry\r\nPintya Darling Aapali Yaari\r\nDholasang Tasha Jaisa\r\nAapala Haay Ek Dujela\r\nDolbywalya Bolaav Mazya DJ La?Bolaav\r\nDolbywalya Bolaav Mazya DJ La?Bolaav(2 Times)\r\n\r\nAre You Ready? Mhanto Bhavadya\r\nLilla Lilla Gaato,\r\nKaay Bi Kar Pan Vaajiv Braazil\r\nDJ Wala Tyala Bhito?DJ(2 Times)\r\nBaachabaachi Ghaalun Raade\r\nDance Bhaari Appudi Pode\r\nMaulich DJ Version Yachya Gharachya Pujela\r\nDolbywalya Bolaav Mazya DJ La?Bolaav\r\nDolbywalya Bolaav Mazya DJ La?Bolaav (2 Times)\r\n\r\nBolaav Mhanje Bolaav\r\nHe Bhavadya Hit It Bhavadya?\r\nBhavadya.. Mind Blowing Bhavadya\r\nBhavadya.. Naachun Ghe Bhavadya', NULL),
(30, 'Painjan', 'AV Prafullchandra', 'Hey are ra ra raa?\r\nPishyavani jhala re\r\nAre ra rara ?.\r\nKhulyavani jhala re\r\nZunjur munjur pahatela\r\nTipur tipur chandane\r\nDivas yeda gela kuthe\r\nBhirbhir najrela najuk sajuk bhaas re\r\n\r\nDaun chanda saral kuthe\r\nBandhavar paay hati aabhal ghavtey\r\nAapsun vare nave urat dhavtaya\r\nPankhaa bigar jeev hyo ud re\r\n\r\nPainjan kana madhe chunu chunu vajatey\r\nDolyasamhor najara pan sapan vatatey (2 Times)\r\n\r\nKa saang sarang aaj gulabi unhacha\r\nPhulavani gandh janu pacholyala aala kasa\r\nKanavar haak jari durvar nahi kuni\r\nDolymhor zop aata zop nah dhyani mani\r\n\r\nHyo.. jeev khelanila pori jeev hyo..\r\nBagh zala item pori\r\nTu gaav bhar unaad zim zim zimmaad\r\nRujale hasale fasale re\r\n\r\nPishyavani jhala re\r\nAre ra rara ?.\r\nKhulyavani jhala re\r\nZunjur munjur pahatela\r\nTipur tipur chandane\r\nDivas yeda gela kuthe\r\nBhirbhir najrela najuk sajuk bhaas re\r\n\r\nBandhavar paay hati aabhal ghavtey\r\nAapsun vare nave urat dhavtaya\r\nPankhaa bigar jeev hyo ud re\r\nDolyasamhor najara pan sapan vatatey\r\n\r\nChunu chunu??.', NULL),
(31, 'हृदयात वाजे सोमेथींग', 'Vidhit Patankar', 'हृदयात वाजे सोमेथींग<br>सारे जग वाटे हाप्पेनिंग<br>असतोस सदा मी आता ड्राइमिंग (2 Times)<br><br>हो…<br>असतो उगाच समिलिंग<br>बघतो तुला मन जम्पिंग<br>वाटे हवे गोड फीलिंग<br>तारणारा<br>असतो उगाच समिलिंग<br>बघतो तुला मन जम्पिंग<br>वाटे हवे गोड फीलिंग<br><br>धुंद धुंद क्षण सारे<br>हलके हलके फुलणारे<br>फिरुनी ओठांवर येई<br>तुझेच गाणे (2 Times)<br><br>खिडकीतून डोकावुनि<br>दिसतेस का पाहतो तुला क्षणोक्षणी<br>काळात तुला मी संपतो<br>रोखू कशी तगमग हि मनाची<br><br>नजरेतूनच माझ्या सांगतो मी तुला सारे<br>समजेल का तुला काही<br>पाहतो जिथे जिथे मी चेहरा तुझाच आहे<br>विसरतो का मलाच मी<br><br>हृदयात वाजे सोमेथींग<br>सारे जग वाटे हाप्पेनिंग<br>असतोस गावी आता ड्राइमिंग (2 Times)<br><br>वाटेवरी मी रोजच्या असतो उभा<br>दिसशील का कधी तरी<br>दिसलीस कि झंकारते<br>उठते मणी किणकिण हि गॉड गॉड अशी<br><br>रोखुनी मला तू बघशी<br>गॉड तू जराशी हसशी<br>ऐशी अन तशीच तू जशी<br>शब्द ना सुचे मग काही<br>बोलणे हि जमतच नाही<br>गोंधळून मन हे जय<br><br>हृदयात वाजे सोमेथींग<br>सारे जग वाटे हाप्पेनिंग<br>असतोस गावी आता ड्राइमिंग (2 Times)', 'https://www.youtube.com/embed/o416zM22IaY'),
(32, 'याडं लागलं ग याडं लागलं गं', 'Ajay Gogavle', 'याडं लागलं ग याडं लागलं गं\r\nरंगलं तुझ्यातं याडं लागलं गं\r\nवास ह्यो उसात येई कस्तूरीचा\r\nचाखलंया वारं ग्वाडं लागलं गं\r\nचांद भासतो दिसाच मावळाया लागलं\r\nआस लागली मनात कालवाया लागलं गं\r\nयाडं लागलं ग याडं लागलं गं…\r\n\r\nयाडं लागलं गं याडं लागलं गं\r\nरंगलो तुझ्यातं याडं लागलं गं\r\nवास ह्यो ऊसातं येई कस्तुरीचा\r\nचाखलया वारं ग्वाड लागलं गं…\r\n\r\nसांगवं ना बोलवं ना मनं झुरतया दुरून\r\nपळतया टळतया वळतयं मागं फिरून…\r\nसजलं रं धजलं रं लाज काजला सारलं\r\nयेंधळ हे गोंधळलं लाङ लाङ गेलं हरुन…\r\nभाळलं असं ऊरातं पालवाया लागलं\r\nहे ओढं लागली मनातं चाळवायां लागलं\r\nयाडं लागलं गं याडं लागलं गं\r\n\r\nहं…\r\n\r\nसुलगं ना ऊलगं ना जाळं आतल्या आतल्या\r\nदुखनं हे देखनं गं एकलचं हाय साथीला\r\nकाजळीला ऊजळलं पाजळूनं ह्या वातीला\r\nचांदणीला आवतन धाडतुया रोजं रातिला\r\nझोप लागना सपानं जागवाया लागलं\r\nपाखरुं कसं…. आभाळ पांघरायां लागलं\r\nहं…\r\nरारीरारीरा रा रारारारा…….', 'https://www.youtube.com/embed/VmU1ZsXUbG0');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `email` text NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `email`, `username`, `password`) VALUES
(1, '', 'Mohit', 'music'),
(2, '', 'praneeth', 'praneeth'),
(3, '', 'hello', 'abcd'),
(5, '', 'deepak', 'deepak'),
(6, '', 'silu', 'silu'),
(7, '', 'sidbot', 'sidbot'),
(8, '', 'anon', 'anon'),
(9, '', 'hey', 'yo'),
(10, '', 'harry', 'harry123'),
(11, '', 'diptesh', 'diptesh'),
(12, '', 'chakri', 'chakri'),
(13, 'mohitkorabu@gmail.com', 'mohit', 'mohit');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `lyrics`
--
ALTER TABLE `lyrics`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `lyrics`
--
ALTER TABLE `lyrics`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
